### ISSUE TITLE
[Bug][3.6.*]: Import of session and config

### ISSUE THREAD

**Issue by nakajiss** [onlinesimio/gateway-soft#13]
### What happened?

**Bug description**
Не  импортируются настройки и данные для входа при миграции со старой библиотеки

**Expected behavior**
При установке софта настройки и сессия должны импортироваться

### Steps to reproduce the behavior?

1. Установить stable версию Simsale Gateway 3.2.40
2. Установить pre-release версию Simsale Gateway 3.6.*

### Priority

middle

### Version

3.6.*

### Environment

Windows 10

**Comment by s00d** [comment]
fixed
