### ISSUE TITLE
[FR] [3.6.*] Autoreset configuration parameters to default values

### ISSUE THREAD

**Issue by alexanderkrsk4** [onlinesimio/gateway-soft#15]
**Issue:** Во время работы (или сразу после запуска приложения) статус порта может смениться на "loading", но номер остается в очереди выдачи. При этом сообщения приходят на номер (и отображаются в оборудовании и логах), но **не передаются на сервер**.

**Suggested solution:** Добавить таймер для статуса "loading", при таймауте которого будет выполняться сброс настроек порта AT-командой AT&F.

**Alternative solution:** Добавить таймер для статуса "loading", при таймауте которого номер будет убран из очереди выдачи.

**UPD:** прикреплены логи, проблема была с многими портами, среди которых были: COM4, COM28, COM61
[log-2021-08-12.log](https://github.com/onlinesimio/gateway-soft/files/6974510/log-2021-08-12.log)

**Comment by nakajiss** [comment]
Закрыто в связи с невозможность воспроизвести баг
