### ISSUE TITLE
[Bug][3.6.50-alpha.2]: Empty ignore list creating bug

### ISSUE THREAD

**Issue by nakajiss** [onlinesimio/gateway-soft#16]
### What happened?

**Bug description**
При нажатии на save, при отсутствии выбранных сервисов в игнор листе, создаётся пустой список

**Expected behavior**
Кнопка неактивна или не создаёт список

**Screenshots**
[Screencast](https://drive.google.com/file/d/1v0PsZnFdtNVBRPRd3_csGD1WDT4Hxjz5/view?usp=sharing)

### Steps to reproduce the behavior?

1. Открыть Simsale Gateway
2. Войти в раздел Settings
3. Перейти к разделу Ignore
4. Нажать Save

### Priority

low

### Version

3.6.50-alpha.2

### Environment

Windows 10

### Relevant log output

```shell
No need
```

**Comment by s00d** [comment]
fixed
