### ISSUE TITLE
[FR] [3.*.*] Adding new connectivity methods

### ISSUE THREAD

**Issue by alexanderkrsk4** [onlinesimio/gateway-soft#17]
Один из реселлеров попросил передать следующее предложение:
> Насколько я понял, на данный момент программа находит модемы следующим образом: сканирует подключённые USB устройства, находит среди них COM-устройства (на Windows) или tty-устройства (на Linux) и тогда их можно добавить в список и работать с ними. Если же модемы подключены не через USB (например, если я пробрасываю модем через TCP соединение), то программа их не видит. Можно ли добавить возможность работать с любыми COM или tty устройствами? Хотя бы для случая, если их явно прописать в конфигурацию json.

**Comment by s00d** [comment]
Мне не на чем такое тестировать, нужен тестовый стенд

**Comment by nakajiss** [comment]
Expired
