### ISSUE TITLE
[Bug][3.6.50-alpha.2]: Autoconnect Bug

### ISSUE THREAD

**Issue by nakajiss** [onlinesimio/gateway-soft#18]
### What happened?

**Bug description**
При автоматическом подключении портов происходит ошибка Critical port error

**Expected behavior**
Порты должны подключаться автоматически

**Screenshots**
[Screencast](https://drive.google.com/file/d/12TQO2C0kIEpdpr0ztGLve7hysYpquUeR/view?usp=sharing)

**Additional context**
На старой версии все работает, порты подключаются, если самостоятельно нажать Connect

### Steps to reproduce the behavior?

1. Открыть Simsale Gateway
2. Перейти на вкладку Ports List
3. Дождаться прогрузки портов и нажать на Connect на любом из портов

### Priority

high

### Version

3.6.50-alpha.2

### Environment

Windows 10

### Relevant log output

[Log](https://drive.google.com/file/d/1h8pdv9CvDcPXfjy0soy5Z7busmpyxFW4/view?usp=sharing)

**Comment by s00d** [comment]
fixed
