### ISSUE TITLE
PHONE NUMBER IMPORT FROM FILE OR BULK ADD

### ISSUE THREAD

**Issue by Emilianocm23** [onlinesimio/gateway-soft#21]
I always need to search for the COM port in the list, then change the phone number because my phone operator doesnt have a USSD code. I would like to have an option that i just load a file on .txt / .json / .csv format and it loads the phone numbers with each port.

Format of the file could be:
```
COM1=PHONE#
COM2=PHONE#
```

Or any format, i just want to save time by bulk importing. 
or it could also just open a modal with a textarea and i can paste the content there and it should link the new phone with the com port

I also work with other provider and in their soft there is this option. It makes work a way easier.

**Comment by nakajiss** [comment]
Reopened in new issue
