### ISSUE TITLE
[Bug][3.6.50-alpha.24]: Неверное название поля повтора пароля

### ISSUE THREAD

**Issue by nakajiss** [onlinesimio/gateway-soft#23]
### What happened?

**Bug description**
Поле повторного ввода пароля  при регистрации нового пользователя имеет название: Telegram username
**Expected behavior**
Название поля: Repeat password
**Screenshots**
https://drive.google.com/file/d/19dV2FDeCPNtEyY2HG0D0vkh6lydQLC1d/view?usp=sharing

### Steps to reproduce the behavior?

1. Открыть Simsale-Gateway
2. Перейти на вкладку Registration
3. Ввести пароль в поле Password

### Priority

low

### Version

3.6.50-alpha.24

### Environment

Windows10/11

**Comment by s00d** [comment]
- fixed
