### ISSUE TITLE
[Bug][3.6.50-alpha.24]: Неверное название кнопок на странице регистрации

### ISSUE THREAD

**Issue by nakajiss** [onlinesimio/gateway-soft#24]
### What happened?

**Bug description**
Неверное название кнопок подтверждения регистрации и перехода к логину: Login (подтверждает регистрацию) и Signin (отправляет на форму авторизации)

**Expected behavior**
Название кнопки должно быть Sign Up (подтверждает регистрацию)  и Login (отправляет на форму авторизации)
**Screenshots**
https://drive.google.com/file/d/1-sGyLj6FRSdL73MP4cD-uFPW19Ers7YL/view?usp=sharing

**Additional info**
Также можно перименовать раздел регистрации с Registration на SignUp в меню

### Steps to reproduce the behavior?

1. Открыть Simsale-Gateway
2. Перейти в раздел регистрации

### Priority

low

### Version

3.6.50-alpha.24

### Environment

Windows10/11

**Comment by s00d** [comment]
- fixed
