### ISSUE TITLE
[Bug][3.6.50-alpha.24]: Некорректное отображение ошибок при регистрации и авторизации

### ISSUE THREAD

**Issue by nakajiss** [onlinesimio/gateway-soft#25]
### What happened?

**Bug description**
Регистрация: 
1.При вводе невалидного ( занятого) имени пользователя регистрация не проходит и сообщения об ошибке нет
2. При вводе невалидной почты регистрация не проходит и выводится неинформативное сообщение об ошибке(см скрин)
3. При оставлении всех полей пустыми выводится неинформативное сообщение об ошибке(такое как на скрине)
4. При оставлении полей почты и имени пользователя нет сообщения об ошибке
Авторизация:  При вводе невалидной пары логин:пароль отсутствует уведомление об ошибке
**Expected behavior**
3.Вывод ошибки, подсказывающих пользователю, что он ввёл неправильно

**Screenshots**
https://drive.google.com/file/d/1fWQY10jtIn9-h_LUdbnujU2khsY4hY-3/view?usp=sharing

### Steps to reproduce the behavior?

1. Открыть Simsale-Gateway
2. Перейти в раздел регистрации
3. Ввести невалидные значения

### Priority

middle

### Version

3.6.50-alpha.24

### Environment

Windows10/11

**Comment by s00d** [comment]
- fixed
