### ISSUE TITLE
[Bug][3.6.50-alpha.24]:  Длинная сумму заработанных средств на номере

### ISSUE THREAD

**Issue by nakajiss** [onlinesimio/gateway-soft#26]
### What happened?

**Bug description**
Длинное число заработанных средств на порту 

**Expected behavior**
Округление после второго знака от запятой

**Screenshots**
https://drive.google.com/file/d/12xptTOAelaCaC7xELkSBAyFCUWDAb5Pv/view?usp=sharing

**Addditional inforamtion**
Номер: 37255933245

### Steps to reproduce the behavior?

1. Открыть Simsale-Gateway
2. Перейти во вкладку Ports list

### Priority

low

### Version

3.6.50-alpha.24

### Environment

Windows10/11

**Comment by s00d** [comment]
- fixed
