### ISSUE TITLE
[Bug][3.6.50-alpha.24]: 

### ISSUE THREAD

**Issue by nakajiss** [onlinesimio/gateway-soft#27]
### What happened?

**Bug description**
Не работает кнопка-ссылка

**Expected behavior**
Кнопка отправляет на репозиторий

**Screenshots**
https://drive.google.com/file/d/1-S2Wo7DJlx_OGkuutYe8A_f41nHbzGL_/view?usp=sharing)

### Steps to reproduce the behavior?

1. Открыть Simsale-Gateway
2. Нажать на кнопку-ссылку

### Priority

low

### Version

3.6.50-alpha.24

### Environment

Windows10/11

**Comment by s00d** [comment]
- fixed
