### ISSUE TITLE
Добавить возможность добавления номеров пачкой

### ISSUE THREAD

**Issue by nakajiss** [onlinesimio/gateway-soft#28]
**Describe the solution you'd like**
Необходимо добавить функционал, позволяющий добавить номера сразу для нескольких портов в виде:
COM1:79999999999

**Comment by Emilianocm23** [comment]
It would be better to have it like this:

79999999999=SIM_ID

There are other platforms like smshub that allow that type of import and it works perfectly.

If anyone is able to develop this for onlinesim soft i can pay for the feature

**Comment by nakajiss** [comment]
Done in beta.2

**Comment by Emilianocm23** [comment]
> Done in beta.2

Where can i find beta.2?

**Comment by nakajiss** [comment]
> > Done in beta.2
> 
> 
> 
> Where can i find beta.2?

We will release it soon when it will be tested
