### ISSUE TITLE
[Bug][3.6.37]: Не работает кнопка Port List

### ISSUE THREAD

**Issue by nakajiss** [onlinesimio/gateway-soft#6]
### What happened?

Не работает кнопка Port List

### Steps to reproduce the behavior?

1. Открыть Simsale-Gateway
2. Нажать на вкладку Port List

### Version

3.6.37

### Environment

Windows 10

### Relevant log output

No need

**Comment by s00d** [comment]
[3.6.38](https://github.com/onlinesimio/gateway-soft/releases/tag/v3.6.38) fixed
