### ISSUE TITLE
[Bug][3.6.38]:Replace IMSI bug 

### ISSUE THREAD

**Issue by nakajiss** [onlinesimio/gateway-soft#7]
### What happened?
Не работает Replace IMSI, не сохраняются значения 
### Screencast/ Screenshot
https://drive.google.com/file/d/1C4uy0WmeTi9Y1v1gVsu3FqXEkXlP6hn1/view?usp=sharing
### Steps to reproduce the behavior?

1. Открыть Simsale-Gateway
2. Открыть вкладку Settings
3. Ввести численные значения в оба поля в разделе Replace "IMSI"

### Priority

middle

### Version

3.6.38

### Environment

Ubuntu 20.04

### Relevant log output

https://drive.google.com/file/d/1oQXhMjfAUb_L4UUXSSxoPyxCzzSbga4L/view?usp=sharing

**Comment by s00d** [comment]
fixed
